# Generated by Django 4.0.3 on 2022-12-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_appointment_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('appointment_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('vip', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['appointment_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='employee_num',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='tech_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.technician'),
        ),
    ]
